apiVersion: apps/v1
kind: Deployment
metadata:
  name: thuchi-app
  namespace: thuchi-app
  labels:
    app: thuchi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thuchi-app
  template:
    metadata:
      labels:
        app: thuchi-app
    spec:
      containers:
      - name: thuchi-app
        image: ghcr.io/hieupcadsc/thuchi:latest  # Sẽ được thay thế bởi CI/CD
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: thuchi-config
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: thuchi-data-pvc
