apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: app
  labels:
    app: nodeapp
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080  # Port có thể truy cập từ bên ngoài
    protocol: TCP
