apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: app
  labels:
    app: nodeapp
spec:
  type: ClusterIP
  selector:
    app: nodeapp
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP