name: CI-CD to Minikube

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted   # chính là runner bạn vừa cài
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create namespace
        run: kubectl create ns app --dry-run=client -o yaml | kubectl apply -f -
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
      - name: Update deployment image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          kubectl -n app set image deploy/nodeapp nodeapp=$IMAGE
          kubectl -n app rollout status deploy/nodeapp
      - name: Show deployment status
        run: kubectl -n app get pods,svc -o wide
